### ISSUE TITLE
[Bug Report] CSS doesn't install/import

### ISSUE THREAD

**Issue by timothymarois** [ly525/material-vue-daterange-picker#56]
CSS doesn't exist nor import:

`import "v-md-date-range-picker/dist/v-md-date-range-picker.css";`

Looking into the vendor files for dist, and there is no CSS. Based on documentation installation, this is not ready out of the box. 

https://ly525.github.io/material-vue-daterange-picker/#quick-start

**Comment by ly525** [comment]
@timothymarois  Thanks for your report, I will take a look and tell you the result tomorrow.

**Comment by timothymarois** [comment]
@ly525 Thanks!

**Comment by ly525** [comment]
@timothymarois 

I'm sorry, it's my fault for not updating the document in time. 
There are some errors in the document about quick-start and installation. I'll update it later.

Actually you do not need to import the css individually, I packed it into the `v-md-date-range-picker.js`. 
I import the css in `Picker.vue`.
I will try to pack the css file individually, which may be a better way.

Ref:
https://github.com/ly525/material-vue-daterange-picker/blob/master/src/components/Picker.vue#L390

Demo:
```html
<html>
  <head>
    <!-- <link rel="stylesheet"
      href="https://unpkg.com/https://unpkg.com/v-md-date-range-picker/dist/v-md-date-range-picker.css"> -->
  </head>
  <body>
    <div id="app">
      <v-md-date-range-picker></v-md-date-range-picker>
    </div>
    <script src="https://unpkg.com/vue"></script>
    <script src="https://unpkg.com/moment"></script>
    <script src="https://unpkg.com/v-md-date-range-picker/dist/v-md-date-range-picker.min.js"></script>
    <script>
      var app = new Vue({
        el: '#app'
      })
    </script>
  </body>
 </html>
```html
